replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: lts
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

pvc:
  enabled: true
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  size: 10Gi

serviceAccount:
  create: true
  name: jenkins-sa
  roleArn: arn:aws:iam::992382695855:role/ExternalSecretsRole


externalSecrets:
  enabled: true
  secretName: jenkins-admin-password
  secretManagerName: my-jenkins-secret
