replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

mongodb:
  username: mongouser
  password: password123
  database: mydatabase

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
