# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Release.Name }}-frontend
#   labels:
#     app: frontend
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: frontend
#          # image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#           image: "{{ .Values.image.repository | default "nginx" }}:{{ .Values.image.tag | default "latest" }}"

#           ports:
#             - containerPort: 3000
# _



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Chart.Name }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: {{ .Chart.Name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Chart.Name }}
#     spec:
#       serviceAccountName: {{ .Values.serviceAccount.name }}
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - containerPort: {{ .Values.service.targetPort }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ include "frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.name" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
