# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-frontend
# spec:
#   selector:
#     app: frontend
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80   # ✅ previously 3000

#   type: NodePort


# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Chart.Name }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   type: {{ .Values.service.type }}
#   selector:
#     app: {{ .Chart.Name }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
