replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

mongodb:
  username: staginguser
  password: stagingpass
  database: stagingdb

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: standard  # Or set to something like "standard" if you're using a cloud provider
