replicaCount: 2

image:
  repository: singhsajal/ecommerce-backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 32001

resources: {}
  # Example:
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

serviceAccount:
  create: true
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}

db:
  host: "myapp-db.xxxxxx.us-east-1.rds.amazonaws.com"
  port: "3306"
  name: "myappdb"
  user: "myappuser"
  password: "mypassword"   # ⚠️ avoid committing real passwords in GitHub