replicaCount: 2
namespace: staging

image:
  repository: singhsajal/ecommerce-backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 32001

resources: {}
  # Example:
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

serviceAccount:
  create: true
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}

db:
  host: "ecomdb.ci7yguk4y2v3.us-east-1.rds.amazonaws.com"
  port: "5432"
  name: "ecomdb"
  user: "dbadmin"
  password: "Focus#9418"   # ⚠️ avoid committing real passwords in GitHub