apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-jenkins-pvc
          serviceAccountIssuerDiscovery:
    discoveryStore: s3://sajalkops-oidc/oidc
    enableAWSOIDCProvider: true
  iam:
    useServiceAccountExternalPermissions: true
  podIdentityWebhook:
    enabled: true
  awsLoadBalancerController:
    enabled: true
