# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-jenkins
#   namespace: jenkins
# spec:
#   type: ClusterIP   # ALB works with ClusterIP
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: jenkins

apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-jenkins
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins



# // test 