apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30080   # access Jenkins on this port
  selector:
    app: jenkins
